export const NFT_PROVIDERS = {
    HIC_ET_NUNC: 'HIC_ET_NUNC',
    KALAMINT: 'KALAMINT',
    PIXEL_POTUS: 'PIXEL_POTUS',
    DOGAMI: 'DOGAMI',
    TWITZ: 'TWITZ',
    H3P: 'H3P',
    BYTEBLOCK: 'BYTEBLOCK',
    ONEOF: 'ONEOF',
    FXHASH: 'FXHASH',
    VERSUM: 'VERSUM',
    RARIBLE: 'RARIBLE',
    EIGHTB: 'EIGHTB',
    IPFS: 'IPFS',

    OBJKT_GENERIC: 'OBJKT_GENERIC',
} as const;
