import { ArtToken, VaultToken, Token, TokenKind } from '../types/general';
import { TRANSACTIONS, COLLECTION } from './TabConstants';
import { NFT_PROVIDERS } from './NFTConstants';


export const knownTokenContracts: (Token | VaultToken | ArtToken)[] = [
    {
        network: 'mainnet',
        address: 'KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9',
        displayName: 'USDtez',
        symbol: 'USDtz',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.usdtz,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 36,
        helpLink: 'https://usdtz.com',
        displayHelpLink: 'usdtz.com',
    },
    {
        network: 'mainnet',
        address: 'KT19at7rQUvyjxnZ2fBv7D9zc8rkyG7gAoU8',
        displayName: 'ETHtez',
        symbol: 'ETHtz',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.ethtz,
        
        scale: 18,
        precision: 18,
        round: 6,
        mapid: 199,
        helpLink: 'https://ethtz.io',
        displayHelpLink: 'ethtz.io',
    },
    {
        network: 'mainnet',
        address: 'KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV',
        displayName: 'Kolibri',
        symbol: 'kUSD',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.kusd,
        
        scale: 18,
        precision: 18,
        round: 2,
        mapid: 380,
        helpLink: 'https://kolibri.finance/',
        displayHelpLink: 'kolibri.finance',
    },
    {
        network: 'mainnet',
        address: 'KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton',
        displayName: 'hic et nunc',
        symbol: 'OBJKT',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt, // TODO: rename to nft
        
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 511,
        nftMetadataMap: 514,
        helpLink: 'https://www.hicetnunc.art/',
        displayHelpLink: 'hicetnunc.art',
        marketAddress: 'KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1EpGgjQs73QfFJs9z7m1Mxm5MTnpC2tqse',
        displayName: 'Kalamint',
        symbol: 'object',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 857,
        nftMetadataMap: 861,
        helpLink: 'https://kalamint.io/',
        displayHelpLink: 'kalamint.io',
        marketAddress: 'KT1EpGgjQs73QfFJs9z7m1Mxm5MTnpC2tqse',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE',
        displayName: 'fx(hash)',
        symbol: 'GENTK',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 22785,
        nftMetadataMap: 22789,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.FXHASH,
        helpLink: 'https://www.fxhash.xyz',
        displayHelpLink: 'fxhash.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW',
        displayName: 'versum',
        symbol: 'VI',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 75550,
        nftMetadataMap: 75556,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.VERSUM,
        helpLink: 'https://www.versum.xyz',
        displayHelpLink: 'versum.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1PooRxUckYjnWVvn9CetZxC9YeG1kkFYW5',
        displayName: 'Mekatron',
        symbol: 'K9',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 81966,
        nftMetadataMap: 81969,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://www.mekatron.club',
        displayHelpLink: 'mekatron.club',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1K6TyRSsAxukmjDWik1EoExSKsTg9wGEEX',
        displayName: 'Tezos Degen Club',
        symbol: 'TDC',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 103533,
        nftMetadataMap: 103538,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://tezosdegenclub.com',
        displayHelpLink: 'tezosdegenclub.com',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1RCzrLhBpdKXkyasKGpDTCcdbBTipUk77x',
        displayName: 'Rare Bears',
        symbol: 'RB',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 109761,
        nftMetadataMap: 109765,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://rarebears.io',
        displayHelpLink: 'rarebears.io',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT18pVpRXKPY2c4U2yFEGSH3ZnhB2kL8kwXS',
        displayName: 'Rarible',
        symbol: 'R',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 55542,
        nftMetadataMap: 55544,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.RARIBLE,
        helpLink: 'https://www.rarible.com',
        displayHelpLink: 'rarible.com',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1Up463qVJqtW5KF7dQZz5SsWMiS32GtBrw',
        displayName: 'OneOf',
        symbol: 'OO',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 12686,
        nftMetadataMap: 12689,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.ONEOF,
        helpLink: 'https://oneof.com',
        displayHelpLink: 'oneof.com',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1Fv8TsEeafDhZXsHCyxFas96YDhXpdmUmz',
        displayName: 'OneOf',
        symbol: 'OO',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 23497,
        nftMetadataMap: 23499,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.ONEOF,
        helpLink: 'https://oneof.com',
        displayHelpLink: 'oneof.com',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1W89JFPhSEph7S1SbgjwTXibdk5t8GYX5p',
        displayName: 'Kumulus',
        symbol: 'KUM',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 19919,
        nftMetadataMap: 19922,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://kumulus-project.com',
        displayHelpLink: 'kumulus-project.com',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1SyPgtiXTaEfBuMZKviWGNHqVrBBEjvtfQ',
        displayName: 'GOGOs',
        symbol: 'GOGO',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 20608,
        nftMetadataMap: 20611,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://gogos.tez.page/',
        displayHelpLink: 'gogos.tez',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1Xf44LpwrA7oBcB3VwWTtUBP1eNRaNnWeh',
        displayName: 'GOGOs Inventory Item',
        symbol: 'GOGOsII',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 89296,
        nftMetadataMap: 89301,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.RARIBLE,
        helpLink: 'https://gogos.tez.page/',
        displayHelpLink: 'gogos.tez',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1MsdyBSAMQwzvDH4jt2mxUKJvBSWZuPoRJ',
        displayName: 'NEONZ',
        symbol: 'NEONZ',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 21217,
        nftMetadataMap: 21220,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://neonz.xyz',
        displayHelpLink: 'neonz.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1CNHwTyjFrKnCstRoMftyFVwoNzF6Xxhpy',
        displayName: 'The Moments',
        symbol: 'MOMENTS',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 21948,
        nftMetadataMap: 21951,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://www.themoments.xyz',
        displayHelpLink: 'themoments.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1HZVd9Cjc2CMe3sQvXgbxhpJkdena21pih',
        displayName: 'Randomly Common Skeles',
        symbol: 'SKELE',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 22381,
        nftMetadataMap: 22384,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://commonskeles.xyz',
        displayHelpLink: 'commonskeles.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1DeFSmknfCG5TveB5DSvrg34hqLcqETNuF',
        displayName: 'TwiTzNFT',
        symbol: 'TWT',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 12357,
        nftMetadataMap: 12360,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.TWITZ,
        helpLink: 'https://twitz.vercel.app/explore',
        displayHelpLink: 'twitz.vercel.app',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1Wm4Cegd7wW6MYxEhg6AH5iFX48y65nWvv',
        displayName: 'Chop Sumo',
        symbol: 'SUMO',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 22648,
        nftMetadataMap: 22650,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://www.chopsumo.xyz/',
        displayHelpLink: 'chopsumo.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1Fxz4V3LaUcVFpvF8pAAx8G3Z4H7p7hhDg',
        displayName: 'Hash Three Points',
        symbol: 'H3P',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 19749,
        nftMetadataMap: 19750,
        helpLink: 'https://h3p.deconcept.com/',
        displayHelpLink: 'h3p.deconcept.com',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1F1mn2jbqQCJcsNgYKVAQjvenecNMY2oPK',
        displayName: 'Pixel',
        symbol: 'PXL',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 21182,
        helpLink: 'https://www.pixelpotus.com/',
        displayHelpLink: 'pixelpotus.com',
    },
    {
        network: 'mainnet',
        address: 'KT1VK8vevaKZNh68fonidY4792yLyrf5Ct3u',
        displayName: 'PixelTACTICs',
        symbol: 'TACTICs',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 36518,
        nftMetadataMap: 36521,
        helpLink: 'https://www.pixeldebates.com/',
        displayHelpLink: 'pixeldebates.com',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1WGDVRnff4rmGzJUbdCRAJBmYt12BrPzdD',
        displayName: 'PixelPotus',
        symbol: 'POTUS',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 5627,
        nftMetadataMap: 5631,
        helpLink: 'https://www.pixelpotus.com/',
        displayHelpLink: 'pixelpotus.com',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1MxGrhSmLPe4W842AutygvuoxUejLJDuWq',
        displayName: 'ByteBlock NFT',
        symbol: 'BB',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 4567,
        nftMetadataMap: 4569,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.BYTEBLOCK,
        helpLink: 'https://byteblock.art/',
        displayHelpLink: 'byteblock.art',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1D394hqndjvTcFgrmUYBxwrzUTNtzrZ5ox',
        displayName: 'Platypoos',
        symbol: 'PP',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 61851,
        nftMetadataMap: 61854,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1FkMRSsrqWXU88PEUuPsjuL9hSEq23R1vD',
        displayName: 'LIGHTFIELDZ',
        symbol: 'LF',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 62771,
        nftMetadataMap: 62774,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1L7GvUxZH5tfa6cgZKnH6vpp2uVxnFVHKu',
        displayName: 'Ottez',
        symbol: 'Ottez',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 88080,
        nftMetadataMap: 88082,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1RiFVovoQbYmYuDPyrEcXjoEKmcoyeSQGh',
        displayName: 'Alt Ottez',
        symbol: 'Alt Ottez',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 102719,
        nftMetadataMap: 102722,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1QYVvQb1NCMWLLSAT7YcYtmmuEiKtTHmwd',
        displayName: 'Ottez Oysters',
        symbol: 'Ottez Oysters',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 137098,
        nftMetadataMap: 137100,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1L3RtW77iYcdmZdYDBu6QzEgFamYrqMTwN',
        displayName: 'Ottez Gen2 Fusion',
        symbol: 'Ottez Gen2 Fusion',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 157931,
        nftMetadataMap: 157933,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1CzVSa18hndYupV9NcXy3Qj7p8YFDZKVQv',
        displayName: 'Mooncakes',
        symbol: 'Mooncakes',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 127310,
        nftMetadataMap: 127316,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://mooncakes.fun',
        displayHelpLink: 'mooncakes.fun',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1GA6KaLWpURnjvmnxB4wToErzM2EXHqrMo',
        displayName: 'Gap Threads',
        symbol: 'Gap',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 77034,
        nftMetadataMap: 77036,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1CAoigsupremoAMdG886B3C2aVUbS1zSRd',
        displayName: 'Factoids!',
        symbol: 'F!',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 51192,
        nftMetadataMap: 51195,
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1WAYmVs8uwG8bMNVvGd4v1GYjSftcLFQTQ',
        displayName: 'raggedz',
        symbol: 'RGGDZ',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 84952,
        nftMetadataMap: 84956,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://www.artforge.io/collections/raggedz',
        displayHelpLink: 'artforge.io',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1VJavBXqdKePeKntrH72BMW87WLXFBnGKt',
        displayName: 'OXTAZY',
        symbol: 'OXTAZY',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 95378,
        nftMetadataMap: 95381,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://oxtazy.xyz',
        displayHelpLink: 'oxtazy.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1QXngq1CCuWv5RtnuYCSvGdKGeBxsRCWvQ',
        displayName: 'Decathlon NFT',
        symbol: 'DEC',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 104097,
        nftMetadataMap: 104100,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1SnUZLQ4gVrQeapUvp6GY9UKKb4gAZJ8D9',
        displayName: 'Doga Bone',
        symbol: 'DB',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 102231,
        nftMetadataMap: 102234,
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
        helpLink: 'https://dogami.com',
        displayHelpLink: 'dogami.com',
    },
    {
        network: 'mainnet',
        address: 'KT1NVvPsNDChrLRH5K2cy6Sc9r1uuUwdiZQd',
        displayName: 'Dogami NFT',
        symbol: 'Dogami',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 115417,
        nftMetadataMap: 115420,
        holderLocation: 'value',
        provider: NFT_PROVIDERS.DOGAMI,
        hideOnLanding: true,
        helpLink: 'https://dogami.com',
        displayHelpLink: 'dogami.com',
    },
    {
        network: 'mainnet',
        address: 'KT1Ha4yFVeyzw6KRAdkzq6TxDHB97KG4pZe8',
        displayName: 'Dogami',
        symbol: 'DOGA',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 5,
        precision: 5,
        round: 2,
        mapid: 134335,
        balancePath: '$.int',
    },
    {
        network: 'mainnet',
        address: 'KT1BRhcRAdLia3XQT1mPSofHyrmYpRddgj3s',
        displayName: 'tzdropz',
        symbol: 'DB',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 111630,
        nftMetadataMap: 111633,
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        hideOnLanding: true,
        helpLink: 'https://tzdropz.com',
        displayHelpLink: 'tzdropz.com/',
    },
    {
        network: 'mainnet',
        address: 'KT1MxDwChiDwd6WBVs24g1NjERUoK622ZEFp',
        displayName: '8bidou',
        symbol: '8B',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 113213,
        nftMetadataMap: 113218,
        holderLocation: 'key',
        balancePath: '$.args[1].int',
        provider: NFT_PROVIDERS.EIGHTB,
        hideOnLanding: true,
        helpLink: 'https://www.8bidou.com',
        displayHelpLink: '8bidou.com',
    },
    {
        network: 'mainnet',
        address: 'KT1VYsVfmobT7rsMVivvZ4J8i3bPiqz12NaH',
        displayName: 'Wrapped Tezos',
        symbol: 'wXTZ',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.wxtz,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 257,
        helpLink: 'https://stakerdao.gitbook.io/stakerdao-faq-and-docs/wrapped-tezos-wxtz-faq-and-docs',
        displayHelpLink: 'stakerdao.gitbook.io',
        vaultCoreAddress: 'KT1V4Vp7zhynCNuaBjWMpNU535Xm2sgqkz6M',
        vaultRegistryMapId: 260,
        vaultList: [],
    },
    {
        network: 'mainnet',
        address: 'KT1KRvNVubq64ttPbQarxec5XdS6ZQU4DVD2',
        displayName: 'Materia',
        symbol: 'MTRIA',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 76310,
    },
    {
        network: 'mainnet',
        address: 'KT1TjnZYs5CGLbmV6yuW169P8Pnr9BiVwwjz',
        displayName: 'objkt.com wrapped xtz',
        symbol: 'oXTZ',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 103270,
        balancePath: '$.args[1].int',
        helpLink: 'https://objkt.com',
        displayHelpLink: 'objkt.com',
    },
    {
        network: 'mainnet',
        address: 'KT1AWoUQAuUudqpc75cGukWufbfim3GRn8h6',
        displayName: 'Flex Fashion',
        symbol: 'FF',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 124575,
        nftMetadataMap: 124577,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://flex.fashion',
        displayHelpLink: 'flex.fashion',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1H436mFXZ1KqCVDUv2YQ23RnqMYKThhqah',
        displayName: 'BatBits',
        symbol: 'BB',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 148210,
        nftMetadataMap: 148212,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://batbits.xyz',
        displayHelpLink: 'batbits.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1LHHLso8zQWQWg1HUukajdxxbkGfNoHjh6',
        displayName: 'Tezzardz',
        symbol: 'FUKR',
        balance: 0,
        transactions: [],
        activeTab: COLLECTION,
        kind: TokenKind.objkt,
        scale: 0,
        precision: 0,
        round: 0,
        mapid: 12112,
        nftMetadataMap: 12115,
        holderLocation: 'key',
        provider: NFT_PROVIDERS.OBJKT_GENERIC,
        helpLink: 'https://tezzardz.xyz',
        displayHelpLink: 'tezzardz.xyz',
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1XpYoPCxQnpgxLM22dkLDXBmTsDLc1S8nZ',
        displayName: 'Trustee Network Token',
        symbol: 'TRU',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 25974,
        balancePath: '$.args[1].int',
        helpLink: 'https://www.tezos.finance',
        displayHelpLink: 'tezos.finance',
    },
    {
        network: 'mainnet',
        address: 'KT1JkoE42rrMBP9b2oDhbx6EUr26GcySZMUH',
        displayName: 'Kolibri DAO Token',
        symbol: 'kDAO',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 18,
        precision: 18,
        round: 6,
        mapid: 7250,
        balancePath: '$.int',
        displayHelpLink: 'kolibri.finance',
        helpLink: 'https://kolibri.finance',
    },
    {
        network: 'mainnet',
        address: 'KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b',
        displayName: 'Plenty',
        symbol: 'PLENTY',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.plenty,
        
        scale: 18,
        precision: 18,
        round: 6,
        mapid: 3943,
        balancePath: '$.args[1].int',
        helpLink: 'https://plentydefi.com',
        displayHelpLink: 'plentydefi.com',
    },
    {
        network: 'mainnet',
        address: 'KT1Rpviewjg82JgjGfAKFneSupjAR1kUhbza',
        displayName: 'xPlenty',
        symbol: 'xPLENTY',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 18,
        precision: 18,
        round: 6,
        mapid: 18153,
        balancePath: '$.int',
        helpLink: 'https://plentydefi.com',
        displayHelpLink: 'plentydefi.com',
    },
    {
        network: 'mainnet',
        address: 'KT1A5P4ejnLix13jtadsfV9GCnXLMNnab8UT',
        displayName: 'Kalamint DAO',
        symbol: 'KALAM',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 10,
        precision: 10,
        round: 5,
        mapid: 4178,
        helpLink: 'https://kalamint.io/',
        displayHelpLink: 'kalamint.io',
    },
    {
        network: 'mainnet',
        address: 'KT1T87QbpXEVgkwsNPzz8iRoah3SS3D1MDmh',
        displayName: 'BTCtez',
        symbol: 'BTCtz',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 0,
        scale: 8,
        precision: 8,
        round: 8,
        mapid: 24117,
        helpLink: 'https://btctz.io/',
        displayHelpLink: 'btctz.io',
    },
    {
        network: 'mainnet',
        address: 'KT1JSYSeLF6bxt8hRXou3Wu4Jdard5vkMkeK',
        displayName: 'URSANITE',
        symbol: 'URSA',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 0,
        scale: 5,
        precision: 5,
        round: 5,
        mapid: 21177,
        helpLink: 'https://rocketmonster.xyz/',
        displayHelpLink: 'rocketmonster.xyz',
    },
    {
        network: 'mainnet',
        address: 'KT1AEfeckNbdEYwaMKkytBwPJPycz7jdSGea',
        displayName: 'Staker Governance Token',
        symbol: 'STKR',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.stkr,
        
        scale: 18,
        precision: 18,
        round: 2,
        mapid: 527,
        helpLink: 'https://docs.stakerdao.com/',
        displayHelpLink: 'stakerdao.com',
    },
    {
        network: 'mainnet',
        address: 'KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW',
        displayName: 'hDAO',
        symbol: 'hDAO',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 515,
        tokenIndex: 0,
    },
    {
        network: 'mainnet',
        address: 'KT1T87QbpXEVgkwsNPzz8iRoah3SS3D1MDmh',
        displayName: 'TezDao',
        symbol: 'TezDao',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 0,
        scale: 6,
        precision: 6,
        round: 6,
        mapid: 72224,
        balancePath: '$.int',
        helpLink: 'https://tezdao.org/',
        displayHelpLink: 'tezdao.org',
    },
    {
        network: 'mainnet',
        address: 'KT1Kyc366SrSJ1camxByr363F9WAiHAaReMv',
        displayName: 'SEXP',
        symbol: 'SEXP',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 18,
        precision: 18,
        round: 6,
        mapid: 22833,
    },
    {
        network: 'mainnet',
        address: 'KT1MEouXPpCx9eFJYnxfAWpFA7NxhW3rDgUN',
        displayName: 'Blend',
        symbol: 'BLND',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.blnd,
        
        scale: 18,
        precision: 18,
        round: 2,
        mapid: 368,
        helpLink: 'https://docs.stakerdao.com/blend-blnd-faq-and-docs',
        displayHelpLink: 'stakerdao.com',
    },
    {
        network: 'mainnet',
        address: 'KT1XTxpQvo7oRCqp85LikEZgAZ22uDxhbWJv',
        displayName: 'GIF DAO',
        symbol: 'GIF',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 9,
        precision: 9,
        round: 4,
        mapid: 7654,
        helpLink: 'https://gif.games',
        displayHelpLink: 'gif.games',
    },
    {
        network: 'mainnet',
        address: 'KT19JYndHaesXpvUfiwgg8BtE41HKkjjGMRC',
        displayName: 'Rocket',
        symbol: 'RCKT',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 4459,
        helpLink: 'https://rocketlaunchpad.io',
        displayHelpLink: 'rocketlaunchpad.io',
    },
    {
        network: 'mainnet',
        address: 'KT1SjXiUX63QvdNMcM2m492f7kuf8JxXRLp4',
        displayName: 'ctez',
        symbol: 'ctez',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 6,
        precision: 6,
        round: 6,
        mapid: 20920,
        balancePath: '$.int',
        displayHelpLink: 'ctez.app',
        helpLink: 'https://ctez.app/',
    },
    {
        network: 'mainnet',
        address: 'KT1LRboPna9yQY9BrjtQYDS1DVxhKESK4VVd',
        displayName: 'WRAP Governance Token',
        symbol: 'WRAP',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 8,
        precision: 8,
        round: 8,
        mapid: 1777,
        helpLink: 'https://www.benderlabs.io/wrap-token',
        displayHelpLink: 'benderlabs.io',
    },
    {
        network: 'mainnet',
        address: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        displayName: 'Wrapped LINK',
        symbol: 'wLINK',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 10,
        scale: 18,
        precision: 8,
        round: 8,
        mapid: 1772,
    },
    {
        network: 'mainnet',
        address: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        displayName: 'Wrapped Matic/Polygon',
        symbol: 'wMATIC',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 11,
        scale: 18,
        precision: 8,
        round: 8,
        mapid: 1772,
    },
    {
        network: 'mainnet',
        address: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        displayName: 'Wrapped Celcius',
        symbol: 'wCEL',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 2,
        scale: 4,
        precision: 4,
        round: 4,
        mapid: 1772,
    },
    {
        network: 'mainnet',
        address: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        displayName: 'Wrapped USDC',
        symbol: 'wUSDC',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 17,
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 1772,
    },
    {
        network: 'mainnet',
        address: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        displayName: 'Wrapped BUSD',
        symbol: 'wBUSD',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 1,
        scale: 18,
        precision: 18,
        round: 2,
        mapid: 1772,
    },
    {
        network: 'mainnet',
        address: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        displayName: 'Wrapped wBTC',
        symbol: 'wwBTC',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 19,
        scale: 8,
        precision: 8,
        round: 8,
        mapid: 1772,
    },
    {
        network: 'mainnet',
        address: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        displayName: 'Ethereum USDC (Plenty)',
        symbol: 'USDC.e',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 2,
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 175082,
    },
    {
        network: 'mainnet',
        address: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        displayName: 'Ethereum WBTC (Plenty)',
        symbol: 'WBTC.e',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 1,
        scale: 8,
        precision: 8,
        round: 8,
        mapid: 175082,
    },
    {
        network: 'mainnet',
        address: 'KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn',
        displayName: 'tzBTC',
        symbol: 'tzBTC',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzbtc,
        
        scale: 8,
        precision: 8,
        round: 8,
        mapid: 31,
        helpLink: 'https://tzbtc.io/',
    },
    {
        network: 'mainnet',
        address: 'KT1KPoyzkj82Sbnafm6pfesZKEhyCpXwQfMc',
        displayName: 'Flame DAO',
        symbol: 'fDAO',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 6,
        mapid: 4828,
        balancePath: '$.args[1].int',
        helpLink: 'https://spacefarm.xyz',
        displayHelpLink: 'spacefarm.xyz',
    },
    {
        network: 'mainnet',
        address: 'KT1Wa8yqRBpFCusJWgcQyjhRz7hUQAmFxW7j',
        displayName: 'Flame Token',
        symbol: 'FLAME',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 6,
        mapid: 2545,
        balancePath: '$.args[1].int',
        helpLink: 'https://spacefarm.xyz',
        displayHelpLink: 'spacefarm.xyz',
    },
    {
        network: 'mainnet',
        address: 'KT193D4vozYnhGJQVtw7CoxxqphqUEEwK6Vb',
        displayName: 'Quipu Governance Token',
        symbol: 'QUIPU',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 6,
        mapid: 12043,
        balancePath: '$.args[0][0].args[1].int',
    },
    {
        network: 'mainnet',
        address: 'KT1REEb5VxWRjcHm5GzDMwErMmNFftsE5Gpf',
        displayName: 'Stably USD',
        symbol: 'USDS',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 397,
    },
    {
        network: 'mainnet',
        address: 'KT1AxaBxkFLCUi3f8rdDAAxBKHfzY8LfKDRA',
        displayName: 'QLkUSD',
        symbol: 'QLkUSD',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 36,
        precision: 36,
        round: 2,
        mapid: 1600,
        helpLink: 'https://kolibri.finance/liquidity-pool',
        displayHelpLink: 'kolibri.finance/liquidity-pool',
    },
    {
        network: 'mainnet',
        address: 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW',
        displayName: 'youves uUSD',
        symbol: 'uUSD',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        tokenIndex: 0,
        
        scale: 12,
        precision: 12,
        round: 2,
        mapid: 7706,
        balancePath: '$.int',
        helpLink: 'https://app.youves.com',
        displayHelpLink: 'app.youves.com',
    },

    {
        network: 'mainnet',
        address: 'KT1Xobej4mc6XgEjDoJoHtTKgbD1ELMvcQuL',
        displayName: 'youves DAO',
        symbol: 'YOU',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        tokenIndex: 0,
        
        scale: 12,
        precision: 12,
        round: 2,
        mapid: 7715,
        balancePath: '$.int',
        helpLink: 'https://app.youves.com',
        displayHelpLink: 'app.youves.com',
    },
    {
        network: 'mainnet',
        address: 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW',
        displayName: 'youves uBTC',
        symbol: 'uBTC',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        tokenIndex: 2,
        
        scale: 12,
        precision: 12,
        round: 2,
        mapid: 7706,
        balancePath: '$.int',
        helpLink: 'https://app.youves.com',
        displayHelpLink: 'app.youves.com',
    },
    {
        network: 'mainnet',
        address: 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW',
        displayName: 'youves DEFI',
        symbol: 'uDEFI',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        tokenIndex: 1,
        
        scale: 12,
        precision: 12,
        round: 4,
        mapid: 7706,
        balancePath: '$.int',
        helpLink: 'https://app.youves.com',
        displayHelpLink: 'app.youves.com',
    },
    {
        network: 'mainnet',
        address: 'KT1CS2xKGHNPTauSh5Re4qE3N9PCfG5u4dPx',
        displayName: 'Spice Token',
        symbol: 'SPI',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        tokenIndex: 0,
        
        scale: 6,
        precision: 6,
        round: 6,
        mapid: 4424,
        balancePath: '$.int',
        helpLink: 'https://spicyswap.xyz',
        displayHelpLink: 'spicyswap.xyz',
    },
    {
        network: 'mainnet',
        address: 'KT1BHCumksALJQJ8q8to2EPigPW6qpyTr7Ng',
        displayName: 'Crunch',
        symbol: 'CRUNCH',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 8,
        precision: 8,
        round: 8,
        mapid: 2809,
    },
    {
        network: 'mainnet',
        address: 'KT1XPFjZqCULSnqfKaaYy8hJjeY63UNSGwXg',
        displayName: 'Crunchy DAO',
        symbol: 'crDAO',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 8,
        precision: 8,
        round: 8,
        mapid: 4666,
    },
    {
        network: 'mainnet',
        address: 'KT1H3LrbC378dPBjTZEK8wVyaknDpQmskRhq',
        displayName: 'ER Ecoworld',
        symbol: 'EREW',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        tokenIndex: 0,
        scale: 8,
        precision: 8,
        round: 8,
        mapid: 5479,
        hideOnLanding: true,
    },
    {
        network: 'mainnet',
        address: 'KT1TwzD6zV3WeJ39ukuqxcfK2fJCnhvrdN1X',
        displayName: 'SmartLink',
        symbol: 'SMAK',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 3,
        precision: 3,
        round: 3,
        mapid: 1798,
        balancePath: '$.args[1].int',
        helpLink: 'https://www.smartlink.so/use-cases/',
        displayHelpLink: 'smartlink.so',
    },
    {
        network: 'mainnet',
        address: 'KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn',
        displayName: 'WTZ',
        symbol: 'WTZ',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        tokenIndex: 0,
        scale: 6,
        precision: 6,
        round: 6,
        mapid: 19486,
    },
    {
        network: 'mainnet',
        address: 'KT1G1cCRNBgQ48mVDjopHjEmTN5Sbtar8nn9',
        displayName: 'Hedgehoge',
        symbol: 'HEH',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 3686,
        balancePath: '$.args[1].int',
        helpLink: 'https://twitter.com/heh_hedgehoge',
        displayHelpLink: '@heh_hedgehoge',
    },
    {
        network: 'mainnet',
        address: 'KT18jyxMDSMJRPPaZjoe49SUkXxax9QZtcWH',
        displayName: 'Four Leaf Clover',
        symbol: 'CLOVER',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip7,
        
        scale: 6,
        precision: 6,
        round: 6,
        mapid: 6114,
        balancePath: '$.args[1].int',
        helpLink: 'https://twitter.com/heh_hedgehoge',
    },
    {
        network: 'mainnet',
        address: 'KT1JBNFcB5tiycHNdYGYCtR3kk6JaJysUCi8',
        displayName: 'Lugh Euro',
        symbol: 'EURL',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 6,
        precision: 6,
        round: 6,
        tokenIndex: 0,
        mapid: 44140,
        balancePath: '$.args[0].int',
        helpLink: 'https://lugh.io',
    },
    {
        network: 'ithacanet',
        address: 'KT1XA22D7DazGGefGVGyWHH9Y2MTFmiPjxq3',
        displayName: 'testUSDtez',
        symbol: 'tUSDtz',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.usdtz,
        
        scale: 6,
        precision: 6,
        round: 2,
        mapid: 34654,
        balancePath: '$.args[1].int',
    },
    {
        network: 'ithacanet',
        address: 'KT1AAfsTHPnWT5cU77CUNQ2dcQNtAJ1jauPC',
        displayName: 'testETHtez',
        symbol: 'tETHtz',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.usdtz,
        
        scale: 18,
        precision: 18,
        round: 2,
        mapid: 34651,
        balancePath: '$.args[1].int',
    },
    {
        network: 'ithacanet',
        address: 'KT1D11fEJQuUGn4m161mHmZ7Lkayzq4Cv6xW',
        displayName: 'testBTCtez',
        symbol: 'tBTCtz',
        balance: 0,
        transactions: [],
        activeTab: TRANSACTIONS,
        kind: TokenKind.tzip12,
        
        scale: 8,
        precision: 8,
        round: 2,
        mapid: 34646,
        tokenIndex: 0,
        balancePath: '$.int',
    },
];

